# Generated by Django 5.2.6 on 2026-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('patients', models.PositiveIntegerField()),
                ('source', models.CharField(default='hospital_system', max_length=100)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_observations',
                'ordering': ['date'],
            },
        ),
    ]
