# Generated by Django 5.2.6 on 2026-10-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('period', models.PositiveIntegerField()),
                ('horizon', models.PositiveIntegerField()),
                ('history_start', models.DateField()),
                ('history_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forecast_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_patients', models.FloatField()),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='src.forecastrun')),
            ],
            options={
                'db_table': 'forecast_points',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('forecast_run', 'date'), name='unique_forecast_point_per_run')],
            },
        ),
    ]
